<a href="https://colab.research.google.com/github/varunonthisside/PyTorch/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Thu Dec 28 12:08:30 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Intro to Tensors

### Creating Tensor

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [2, 4, 6],
                        [3, 6, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 4, 6],
         [3, 6, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

### Random Tensors

Tensors start with random numbers and adjust those random numbers to better represent the data

In [ ]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6008, 0.4806, 0.0782, 0.2473],
        [0.2475, 0.7909, 0.8698, 0.7106],
        [0.4221, 0.1362, 0.1453, 0.9649]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a random tensor with  similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #color channel, ht, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

###zeroes and ones

In [ ]:
# create a tensor of all zeroes
zero = torch.zeros(size=(3, 4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor of all ones
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

###Create a range of tensors and tensors-like

In [ ]:
#use torch.range()
one_to_K = torch.arange(start= 0, end = 1000, step = 10)
one_to_K

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270,
        280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410,
        420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550,
        560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690,
        700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830,
        840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970,
        980, 990])

In [ ]:
#creating tensors-like
one_to_K.shape
ten_zeros = torch.zeros_like(input = one_to_K)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

###Tensor Datatypes

####Errors might pop up


In [ ]:
#Float32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, #what datatype
                               device = None, #what device is your tensor on
                               requires_grad= False) # whether or not to track gradiens with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting info from Tensors

In [ ]:
# Create a tensor
some_tensor = torch.rand( 3,4)
some_tensor

tensor([[0.0701, 0.3291, 0.9975, 0.1065],
        [0.6520, 0.1295, 0.4206, 0.1574],
        [0.5555, 0.2099, 0.2342, 0.0318]])

In [ ]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of Tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0701, 0.3291, 0.9975, 0.1065],
        [0.6520, 0.1295, 0.4206, 0.1574],
        [0.5555, 0.2099, 0.2342, 0.0318]])
Datatype of Tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### tensor manipulation (tensor operation)


*   Addition
*   Subtraction
*   Multiplication (element-wise)
*   Division
*   Matrix Multiplication

In [ ]:
#create a tensor add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#Multiply by 10
tensor_mul = tensor * 10
tensor_mul

tensor([10, 20, 30])

In [ ]:
tensor_dif = tensor - 10
tensor_dif

tensor([-9, -8, -7])

In [ ]:
#Pytorch inbuilt functions
torch.add(tensor, 10)
torch.mul(tensor, 10)
torch.subtract(tensor, 10)

tensor([-9, -8, -7])

### Matrix Multiplication

Two main ways to perform X in NN and DL

1. Element-Wise
2. Matrix Multiplication (dot product)

In [ ]:
#Element wise X
tensor

tensor([1, 2, 3])

In [ ]:
print(tensor, "*", tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [ ]:
torch.matmul(tensor, tensor)


tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 464 µs, sys: 0 ns, total: 464 µs
Wall time: 515 µs


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 34 µs, sys: 0 ns, total: 34 µs
Wall time: 37.2 µs


tensor(14)

In [ ]:
### One of the most common errors in DL is shape errors
### 1. inner dimension must match
###    (x,y)(y,z) --> y must be same

### 2. resulting matrix has the shape of the outer dimensions:
###    res = (x,z)

In [ ]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.2544, 0.4386],
        [0.7284, 0.7738]])

In [ ]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
#torch.mm == torch.matmul
#torch.mm(tensor_A,tensor_B)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
### Transpose: used to fix shape errors.
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [ ]:
# the matmul ops works when tensor B is transposed
print(f"Original shape: tensorA = {tensor_A.shape}, tensorB = {tensor_B.shape}")
print(f"New shape: tensorA = {tensor_A.shape}, tensorB.T = {tensor_B.T.shape}")
print(f"multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dims must match")
print("Output: \n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\n output shape: {output.shape}")

Original shape: tensorA = torch.Size([3, 2]), tensorB = torch.Size([3, 2])
New shape: tensorA = torch.Size([3, 2]), tensorB.T = torch.Size([2, 3])
multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dims must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

 output shape: torch.Size([3, 3])


### Tensor Aggregation
### Min, max, mean, sum, etc

In [ ]:
# create a t4nsor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
#max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
#argmin --> find positional aggr
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [ ]:
#argmax
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

### Reshaping, Stacking, Squeezing and Unsqueezing Tensors



*   Reshaping - reshapes an input tensor to defined shape
*   view - return a view of an input tensor of certain shape but keep the same memory as original tensor
*   stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
*   squeeze - removes all 1 dimensions from a tensor
*   unsqueeze - add a 1 dimension to a target tensor
*   permute - return a view of input with dimensions permuted in a certain way




In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 9.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x (because view of a tensor shares the same memory as the original tensor)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#squeeze - removes all 1 dimension from tensors
# torch.squeeze

x = torch.zeros(2, 1, 2, 1, 2)
x.size()
y = torch.squeeze(x)
y.size()
y = torch.squeeze(x, 0)
y.size()
y = torch.squeeze(x, 1)
y.size()
y = torch.squeeze(x, (1, 2, 3))

In [ ]:
print(f"Previos tensor: {x_reshaped}")
print(f"Prev shape: {x_reshaped.shape}")

#remove extra dims from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previos tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Prev shape: torch.Size([9, 1])

New Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
x_reshaped.shape

torch.Size([9, 1])

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
# torch.unsqueeze() - adds a single dim to a target tensor at a specific dim
print(f"prev target: {x_squeezed}")
print(f"prev shape: {x_squeezed.shape}")

#Add an extra dim with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"new shape: {x_unsqueezed.shape}")

prev target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
prev shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new shape: torch.Size([1, 9])


In [ ]:
# torch.permute -rearranges the dim of target tensors in a specified order
x_original = torch.rand(size=(224,224,3)) # [ht, width, color_channel]

#permute the og tensor to rearrange the axis (or dim) order
x_perm = x_original.permute(2, 0 ,1) #shift axis 0->1, 1->2, 2->0

print(f"prev shape: {x_original.shape}")
print(f"new shape: {x_perm.shape}")

prev shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0] = 0.2411
x_perm[0, 0, 0]

tensor(0.2411)

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to NumPy

In [ ]:
#Create a tensor
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#Let's index on the new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
##Let's index on middle bracket (dim =1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
##index on the most inner bracket (last dim)
x[0][0][0]

tensor(1)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
## use ":" to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
#get all values of 0th and 1st dim but only index 1 and 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
#get all values of the 0 dim but only the 1 index value of 1st and 2nd dim
x[:,1,1]

tensor([5])

In [ ]:
#get index 0 of 0th and 1st dim and all values of the second dim
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
#index on x to return 9
print(x[0][0][2])

#index on x to return 3,6,9
print(x[:,:,2])

tensor(3)
tensor([[3, 6, 9]])


##PyTorch tensors and NumPy

PyTorch has functionality to interact with it

* data in numpy, want in pytorch tensor -> torch.from_numpy(ndarray)
* pytorch tensor --> numpy-> torch.Tensor.numpy()

In [ ]:
#numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype
# numpy -> tensor: by default dtype of tensor will be same as array type unless specified

torch.float32

In [ ]:
array = array + 1
array, tensor
#new tensor in memory, will not change

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
#tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#change the tensor, what happens to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability (trying to take the random out of random)

in short how a NN learns:

`start with random numbers -> tensor ops ->update random numbers to try and make them better representation of data -> again -> again -> ...`

to reduce the randomness in NN and pytorch comes the concept of **random seed**.


In [ ]:
torch.rand(3,3)

tensor([[0.4199, 0.8592, 0.3158],
        [0.7243, 0.5899, 0.4699],
        [0.5142, 0.8468, 0.3356]])

In [ ]:
import torch
#create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7539, 0.1952, 0.0050, 0.3068],
        [0.1165, 0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913, 0.1447]])
tensor([[0.5315, 0.1587, 0.6542, 0.3278],
        [0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#let's make some random but reproducible tensors

import torch

#set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)    #set random seed everytime you create a tensor
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pytorch objects on the gpus


### 1. Getting a GPU

1. Easiest: Use Colab for free GPU
2. Use your own GPU
3. Use cloud computing

In [ ]:
!nvidia-smi

Fri Dec 29 06:33:14 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

#check for GPU access with pytorch

In [ ]:
#check for GPU access
import torch
torch.cuda.is_available()

True

In [ ]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#count number of devices
torch.cuda.device_count()

1

## Putting tensors on the GPU

GPU == Speed

In [ ]:
#create a tensor (default on cpu)
tensor = torch.tensor([1,2,3])

##tensor not on gpu
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to GPU
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to CPU

In [ ]:
#if tensor is on gpu, can't transform it to numpy
#tensor_gpu.numpy() #error: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

tensor_back_on_cpu = tensor_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_gpu

tensor([1, 2, 3], device='cuda:0')